# Site settings
title: "ail: 千葉大学 建築情報研究室（加戸研究室）"
description: "Architectual Information Laboratory (kado-lab), Chiba University"
description_jp: 千葉大学 建築情報研究室（加戸研究室）
url: "https://ail-and-colleagues.github.io"
author:
  name: "keita KADO"
  url: "https://ail-and-colleagues.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
rooturl: https://ail-and-colleagues.github.io/
repourl: https://github.com/ail-and-colleagues/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Plugins
plugins:
 - jekyll-sitemap

sitemap:
    path: sitemap.xml
    template: ./sitemap_template.xml
    rel: false
    